version: '3.8'

services:
  claude-docker:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        USERNAME: node
        GROUP: node
        CLAUDE_CODE_VERSION: latest
    image: ytz-ai-agent-image 
    container_name: ytz-ai-agent
    # network_mode: "host"
    ports:
      - "9000:8000"  # API服务端口
    env_file:
      - ../.env
    environment:
      - ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic
      - GITLAB_BASE_URL=http://git-internal.nie.netease.com/
    volumes:
      - ~/.ssh:/home/node/.ssh:ro
      # - ~/monorepo:/workspace/monorepo